title: soultree1984's blog
sub_title: 그리고 봄이 올것이다.
email: soulate@gmail.com
description: |
  걱정하지 마라. 포기하지 마라. 후회하지 마라.
baseurl: ''
url: 'https://soultree1984.github.io'
timezone: Asia/Seoul

#repository: kakao/kakao.github.io
repository: soultree1984/soultree1984.github.io

#permalink: /:categories/:title
permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 2
  limit: 0
  sort_field: 'date'
  sort_reverse: true


collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/


exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]
github: [metadata]
# iolo's custom
author: opensource@kakaocorp.com
image: '/assets/images/cover4.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: 'UA-72007721-1'

github_url:
  username: soultree1984
